name: Commit

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  run:
    name: Commit
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚀 Run
        shell: bash
        run: |
          python3 treeTest.py