name: Commit

on:
  commit:
    branches:
      - main

jobs:
  run:
    name: Commit
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚀 Run
        shell: bash
        run: |
          python3 treeTest.py